import os
import re
import pandas as pd
import matplotlib.pyplot as plt

# Directory Configuration
CSV_DIR = "/home/emanuele/Documenti/Magistrale/NLU-2026-Labs/exam/258437_Emanuele_Ricca/export_csv_tensorboard"
OUTPUT_DIR = "/home/emanuele/Documenti/Magistrale/NLU-2026-Labs/exam/258437_Emanuele_Ricca/LM/report/images"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# TensorBoard Metric Tag Configuration
LINE_METRICS = {
    'loss_train': 'loss/train',
    'ppl_dev': 'ppl/dev'
}
BAR_METRIC_TAG = 'ppl/test'

# Mapping config names to your specific suffix format
SUFFIX_MAP = {
    "only_1A": "_1a",
    "only_1B": "_1b",
    "1A_plus_1B": "_1a_1b",
    "only_2A": "_2a",
    "only_2B": "_2b",
    "2A_plus_2B": "_2a_2b"
}

def clean_label(run_name):
    # Dictionary tracking unique substrings from your 1A folders to their clean LaTeX names
    mapping_1A = {
        "1A_20260514_174737_Baseline": "Baseline Layout",
        "1A_20260514_185306_Bigger_d_model": r"+ Bigger $d_{\text{model}}$ (32, $ff_{\text{dim}}=64$)",
        "more_layers_+_bigger_d_model_(decreased_lr)": "+ More Layers",
        "more_heads_+_more_layers_+_bigger_d_model_(decreased_lr)": "+ More Heads",
        "emb_dropout_0.2": "+ Embedding Dropout (0.2)",
        "weight_tying_+_more_heads": r"+ Weight Tying (WT, $lr=0.01$)",
        "emb_dropout_0.05": "+ Embedding Dropout (0.05)",
        "attn_dropout_0.05": "+ Attention Dropout (0.05)",
        "ff_dropout_0.1_+_more_heads_+_more_layers": "+ Feed-Forward Dropout (0.1)",
        "proj_dropout_0.05": "+ Projection Dropout (0.05)",
        "202527_wt_+_ff_dropout_0.1": r"+ WT + FF Drop 0.1 ($lr=0.005$)",
        "213348_wt_+_ff_dropout_0.1": r"+ WT + FF Drop 0.1 ($lr=0.005$)"
    }
    
    if run_name.startswith("1A_"):
        for key, target_label in mapping_1A.items():
            if key in run_name:
                return target_label
                
    # Fallback for 1B, 2A, 2B
    match = re.search(r'\d{8}_\d{6}_(.+)$', run_name)
    if match:
        return match.group(1).replace('_', ' ')
        
    return run_name

# Find all CSV files generated by your export process
csv_files = [f for f in os.listdir(CSV_DIR) if f.startswith("export_") and f.endswith(".csv")]

print(f"Found {len(csv_files)} configurations to plot.\n")

for csv_file in csv_files:
    config_name = csv_file.replace("export_", "").replace(".csv", "")
    
    # Get the file suffix (e.g., '_1a_1b'), skip if the config name isn't recognized
    suffix = SUFFIX_MAP.get(config_name)
    if not suffix:
        continue
        
    csv_path = os.path.join(CSV_DIR, csv_file)
    df = pd.read_csv(csv_path)
    
    if df.empty:
        continue
        
    print(f"Processing Group: [{config_name}] -> Suffix: {suffix}")
    
    # ==========================================
    # 1. GENERATE LINE PLOTS (Train Loss & Dev PPL)
    # ==========================================
    for base_name, board_tag in LINE_METRICS.items():
        metric_df = df[df['Metric'] == board_tag]
        if metric_df.empty:
            continue
            
        plt.figure(figsize=(7, 4.5))
        for run_name in metric_df['Run'].unique():
            run_df = metric_df[metric_df['Run'] == run_name].sort_values(by='Step')
            plt.plot(run_df['Step'], run_df['Value'], label=clean_label(run_name), linewidth=1.5)
        
        plt.xlabel('Steps', fontsize=11, fontweight='semibold')
        plt.ylabel('Loss' if 'loss' in base_name else 'Perplexity (PPL)', fontsize=11, fontweight='semibold')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.legend(loc='best', fontsize=9, framealpha=0.9)
        plt.tight_layout()
        
        # Saves as flat file like: loss_train_1a_1b.svg
        target_path = os.path.join(OUTPUT_DIR, f"{base_name}{suffix}.svg")
        plt.savefig(target_path, format='svg', bbox_inches='tight')
        plt.close()
        print(f" 🎨 Saved line plot: {target_path}")
        
    # ==========================================
    # 2. GENERATE HORIZONTAL BAR CHART (Test PPL)
    # ==========================================
    test_df = df[df['Metric'] == BAR_METRIC_TAG]
    if not test_df.empty:
        final_scores = []
        for run_name in test_df['Run'].unique():
            run_data = test_df[test_df['Run'] == run_name].sort_values(by='Step')
            final_val = run_data['Value'].iloc[-1]
            final_scores.append({
                'CleanRun': clean_label(run_name),
                'Value': final_val
            })
        
        bar_df = pd.DataFrame(final_scores).sort_values(by='Value', ascending=False)
        
        plt.figure(figsize=(7, max(3, len(bar_df) * 0.45)))
        bars = plt.barh(bar_df['CleanRun'], bar_df['Value'], color='#2b5c8f', edgecolor='black', height=0.6)
        
        plt.xlabel('Final Test Perplexity (Lower is Better)', fontsize=11, fontweight='semibold')
        plt.grid(axis='x', linestyle='--', alpha=0.6)
        
        for bar in bars:
            width = bar.get_width()
            plt.text(width + (width * 0.01), 
                     bar.get_y() + bar.get_height()/2, 
                     f'{width:.2f}', 
                     va='center', ha='left', fontsize=9, fontweight='semibold')
                     
        plt.xlim(0, max(bar_df['Value']) * 1.15)
        plt.tight_layout()
        
        # Saves as flat file like: ppl_test_1a_1b.svg
        target_path = os.path.join(OUTPUT_DIR, f"ppl_test{suffix}.svg")
        plt.savefig(target_path, format='svg', bbox_inches='tight')
        plt.close()
        print(f" 📊 Saved bar chart: {target_path}")
        
    print()

print("✨ Done! All configuration files exported to a flat directory.")